<?php
/**
 * Plugin Name: NH3 Mag - Translated Custom Content
 * Description: Manage translated custom content (such as categories name) for the NH3 Mag theme
 * Version:     1.0.0
 * Author:      MEI
 * Author URI:  https://heig-vd.ch/rad/instituts/mei/
 * Text Domain: nh3-mag-translated-custom-content
 * Domain Path: /languages
 */

// THIS FILE IS AUTOMATICALLY GENERATED !
// DO NOT ALTER ITS CONTENT

// Main plugin file path
define( 'NH3_MAG_TRANSLATED_CUSTOM_CONTENT_MAIN_FILE', __FILE__ );

// Bootstrap the plugin.
require_once 'bootstrap.php';
